name: Check pull request
on:
  pull_request:
    branches:
    - main
    - develop

jobs:
  Build_Meridian_LITE_for_ESP32:
    uses: ./.github/workflows/_WORKFLOW_CALL_RunningPlatformIO.yml
    with:
      target_dir: Meridian_LITE_for_ESP32
      board_env: esp32dev
      firmware_name: Meridian_LITE_for_ESP32
  Build_Meridian_LITE_for_teensy40:
    uses: ./.github/workflows/_WORKFLOW_CALL_RunningPlatformIO.yml
    with:
      target_dir: Meridian_LITE_for_ESP32
      board_env: teensy40
      firmware_name: Meridian_LITE_for_teensy40
  Build_Meridian_LITE_for_pico:
    uses: ./.github/workflows/_WORKFLOW_CALL_RunningPlatformIO.yml
    with:
      target_dir: Meridian_LITE_for_ESP32
      board_env: pico
      firmware_name: Meridian_LITE_for_pico
